/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ashwi
 */
public class billpanel extends javax.swing.JPanel
{

    /**
     * Creates new form billpanel
     */
                  
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    int total=0;
    public billpanel()
    {
        initComponents();
        
    }

    
    void buybook(String name,int price)
    {
        String booktxt=txtareabooks.getText();
        booktxt=booktxt+"\n"+name;
        txtareabooks.setText(booktxt);
        
        String pricetxt=txtareaprice.getText();
        pricetxt=pricetxt+"\n"+price;
        txtareaprice.setText(pricetxt);
        
        
        total=total+price;
        lbltotal.setText(""+total);
        System.out.println(booktxt);
        
           
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        mainpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareabooks = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtareaprice = new javax.swing.JTextArea();
        lbltotal = new javax.swing.JLabel();
        lbltittle = new javax.swing.JLabel();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setPreferredSize(new java.awt.Dimension(330, 410));

        mainpanel.setBackground(new java.awt.Color(189, 148, 121));
        mainpanel.setLayout(null);

        txtareabooks.setColumns(12);
        txtareabooks.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        txtareabooks.setRows(5);
        jScrollPane1.setViewportView(txtareabooks);

        mainpanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 190, 320);

        txtareaprice.setColumns(6);
        txtareaprice.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        txtareaprice.setRows(5);
        jScrollPane3.setViewportView(txtareaprice);

        mainpanel.add(jScrollPane3);
        jScrollPane3.setBounds(210, 30, 110, 320);

        lbltotal.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 36)); // NOI18N
        mainpanel.add(lbltotal);
        lbltotal.setBounds(210, 360, 110, 40);

        lbltittle.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 36)); // NOI18N
        lbltittle.setText("Total :");
        mainpanel.add(lbltittle);
        lbltittle.setBounds(100, 360, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lbltittle;
    private javax.swing.JLabel lbltotal;
    public javax.swing.JPanel mainpanel;
    public javax.swing.JTextArea txtareabooks;
    private javax.swing.JTextArea txtareaprice;
    // End of variables declaration//GEN-END:variables
}
