/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

//import .sellBooks;
//import files.update_data;

/**
 *
 * @author Lenovo
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setSize(this.getWidth(),this.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        btnupdate = new javax.swing.JLabel();
        btnsell = new javax.swing.JLabel();
        btnstats = new javax.swing.JLabel();
        btnavailability = new javax.swing.JLabel();
        lblhome = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnupdateMouseClicked(evt);
            }
        });
        jPanel1.add(btnupdate);
        btnupdate.setBounds(160, 70, 290, 180);

        btnsell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsell.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnsellMouseClicked(evt);
            }
        });
        jPanel1.add(btnsell);
        btnsell.setBounds(540, 70, 290, 180);

        btnstats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnstats.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnstatsMouseClicked(evt);
            }
        });
        jPanel1.add(btnstats);
        btnstats.setBounds(540, 310, 290, 200);

        btnavailability.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnavailability.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnavailabilityMouseClicked(evt);
            }
        });
        jPanel1.add(btnavailability);
        btnavailability.setBounds(160, 320, 290, 180);

        lblhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblhome.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblhomeMouseClicked(evt);
            }
        });
        jPanel1.add(lblhome);
        lblhome.setBounds(940, 490, 60, 60);

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashwi\\Documents\\NetBeansProjects\\bookStoreManagement\\src\\main\\java\\images\\dashboard.png")); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, 0, 1070, 568);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
        // TODO add your handling code here:
        update_data ref=new update_data();
        ref.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnupdateMouseClicked

    private void btnsellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsellMouseClicked
        // TODO add your handling code here:
        sellBooks obj=new sellBooks();
        obj.setVisible(true);
        System.out.println("clicked");
        this.dispose();
    }//GEN-LAST:event_btnsellMouseClicked

    private void btnavailabilityMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnavailabilityMouseClicked
    {//GEN-HEADEREND:event_btnavailabilityMouseClicked
        // TODO add your handling code here:
        stock ref=new stock();
        ref.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnavailabilityMouseClicked

    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblhomeMouseClicked
    {//GEN-HEADEREND:event_lblhomeMouseClicked
        // TODO add your handling code here:
        login lg=new login();
        lg.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_lblhomeMouseClicked

    private void btnstatsMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnstatsMouseClicked
    {//GEN-HEADEREND:event_btnstatsMouseClicked
        // TODO add your handling code here:
        Statistics stats=new Statistics();
        stats.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnstatsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnavailability;
    private javax.swing.JLabel btnsell;
    private javax.swing.JLabel btnstats;
    private javax.swing.JLabel btnupdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblhome;
    // End of variables declaration//GEN-END:variables
}
