/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package source;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ashwi
 */
public class login extends javax.swing.JFrame {
    
    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
   
    

    /** Creates new form login */
    public login() {
        initComponents();
         conn=javaconnect.connerDb();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainpanel = new javax.swing.JPanel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnsubmit = new javax.swing.JButton();
        lblexit = new javax.swing.JLabel();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 600));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1014, 568));
        getContentPane().setLayout(null);

        mainpanel.setBackground(new java.awt.Color(60, 86, 84));
        mainpanel.setLayout(null);

        txtusername.setBackground(new java.awt.Color(241, 241, 207));
        txtusername.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtusername.setToolTipText("Enter Username");
        txtusername.setAlignmentY(1.0F);
        txtusername.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtusername.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtusernameActionPerformed(evt);
            }
        });
        mainpanel.add(txtusername);
        txtusername.setBounds(270, 250, 360, 30);

        txtpassword.setBackground(new java.awt.Color(241, 241, 207));
        txtpassword.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtpassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        mainpanel.add(txtpassword);
        txtpassword.setBounds(270, 370, 360, 30);

        btnsubmit.setBackground(new java.awt.Color(153, 153, 255));
        btnsubmit.setText("SUBMIT");
        btnsubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsubmitActionPerformed(evt);
            }
        });
        mainpanel.add(btnsubmit);
        btnsubmit.setBounds(470, 420, 73, 28);

        lblexit.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashwi\\Documents\\NetBeansProjects\\bookStoreManagement\\src\\main\\java\\images\\black_cross.png")); // NOI18N
        lblexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblexit.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblexitMouseClicked(evt);
            }
        });
        mainpanel.add(lblexit);
        lblexit.setBounds(970, 10, 40, 40);

        lblbackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashwi\\Documents\\NetBeansProjects\\bookStoreManagement\\src\\main\\java\\images\\login_bg.png")); // NOI18N
        mainpanel.add(lblbackground);
        lblbackground.setBounds(-30, 0, 1050, 570);

        getContentPane().add(mainpanel);
        mainpanel.setBounds(0, 0, 1020, 570);

        setSize(new java.awt.Dimension(1014, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsubmitActionPerformed
    {//GEN-HEADEREND:event_btnsubmitActionPerformed
        try
        {

            Statement st=conn.createStatement();

            String uname=txtusername.getText();
            String pwd=txtpassword.getText();

            String str="Select * from employees where username = '" + uname +"' and password = '"+pwd+"'";

            ResultSet rs;

            rs=st.executeQuery(str);
            
            if(rs.first())
            {
                JOptionPane.showMessageDialog(null,"Logged in Successfully");
                Dashboard dbDashboard= new Dashboard();
                dbDashboard.setVisible(true);
                this.dispose();
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid credentials");
                txtusername.setText("");
                txtpassword.setText("");
            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"Error "+e);
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtusernameActionPerformed
    {//GEN-HEADEREND:event_txtusernameActionPerformed
        // TODO add your handling code here:
        txtpassword.requestFocus();
        
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtusernameFocusLost
    {//GEN-HEADEREND:event_txtusernameFocusLost

    }//GEN-LAST:event_txtusernameFocusLost

    private void lblexitMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblexitMouseClicked
    {//GEN-HEADEREND:event_lblexitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblexitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblexit;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

}
