/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import source.Dashboard;


public class sellBooks extends javax.swing.JFrame implements Runnable
{

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    billpanel bp=new billpanel();
    Thread t;
    
    public sellBooks()
    {
        initComponents();
         
        
         conn=javaconnect.connerDb();
         bp.setBounds(0, 0,billpane.getWidth(),billpane.getHeight());
         CommonFunctions.switchPanel(billpane,bp);
         
         t=new Thread(this);
         
    }
    public void run()
    {
        
        printinganimation pa=new printinganimation();
        pa.setBounds(0, 0,billpane.getWidth(),billpane.getHeight());
        CommonFunctions.switchPanel(billpane,pa);
        try
        {
            System.out.println("int try ");
            Thread.sleep(4000);
            System.out.println("in try");
        } catch (InterruptedException ex)
        {
            Logger.getLogger(sellBooks.class.getName()).log(Level.SEVERE, null, ex);
        }
        bp=new billpanel();
        bp.setBounds(0, 0,billpane.getWidth(),billpane.getHeight());
        CommonFunctions.switchPanel(billpane,bp);
      
    
    }
    private void addToBill()
    {
          try {
            String bookid=txtid.getText();
             String sql="select * from books where Id ="+bookid;
         
             pst=conn.prepareStatement(sql);
             rs=pst.executeQuery();
             
             if(rs.next())
           {

                String name=rs.getString("Name");
                int price=rs.getInt("Price");
                System.out.println(name);
                
                bp.buybook(name,price);
                
                sql="update books set Quantity = Quantity-1 where Id="+bookid;
                pst=conn.prepareStatement(sql);
                pst.executeUpdate();
            }
            
           else 
           {
              JOptionPane.showMessageDialog(null,"No data Found.Please try again!!!");
            }
        } 
        catch (Exception e) 
        {
           JOptionPane.showMessageDialog(null, "It is not connceted.");
        }
        
        finally
        {   
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }
    
    private void resetBill()
    {
        bp=new billpanel();
        bp.setBounds(0, 0,billpane.getWidth(),billpane.getHeight());
        CommonFunctions.switchPanel(billpane,bp);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainpanel = new javax.swing.JPanel();
        txtid = new javax.swing.JTextField();
        billpane = new javax.swing.JLayeredPane();
        lblgenerateBill = new javax.swing.JLabel();
        lblhome = new javax.swing.JLabel();
        btnsearch = new javax.swing.JLabel();
        lblreset = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1014, 568));
        setResizable(false);
        setSize(new java.awt.Dimension(1014, 568));

        mainpanel.setBackground(new java.awt.Color(255, 255, 255));
        mainpanel.setLayout(null);

        txtid.setBackground(new java.awt.Color(98, 83, 74));
        txtid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtid.setForeground(new java.awt.Color(220, 171, 139));
        txtid.setText("Enter Book ID");
        txtid.setToolTipText("Enter book id");
        txtid.setRequestFocusEnabled(false);
        txtid.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                txtidFocusGained(evt);
            }
        });
        txtid.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtidActionPerformed(evt);
            }
        });
        mainpanel.add(txtid);
        txtid.setBounds(90, 70, 320, 40);

        javax.swing.GroupLayout billpaneLayout = new javax.swing.GroupLayout(billpane);
        billpane.setLayout(billpaneLayout);
        billpaneLayout.setHorizontalGroup(
            billpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        billpaneLayout.setVerticalGroup(
            billpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        mainpanel.add(billpane);
        billpane.setBounds(590, 110, 330, 410);

        lblgenerateBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblgenerateBill.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblgenerateBillMouseClicked(evt);
            }
        });
        mainpanel.add(lblgenerateBill);
        lblgenerateBill.setBounds(330, 160, 170, 60);

        lblhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblhome.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblhomeMouseClicked(evt);
            }
        });
        mainpanel.add(lblhome);
        lblhome.setBounds(950, 490, 60, 60);

        btnsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsearch.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnsearchMouseClicked(evt);
            }
        });
        mainpanel.add(btnsearch);
        btnsearch.setBounds(450, 60, 50, 60);

        lblreset.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashwi\\Documents\\NetBeansProjects\\bookStoreManagement\\src\\main\\java\\images\\reset.png")); // NOI18N
        lblreset.setToolTipText("reset the cart");
        lblreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblreset.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblresetMouseClicked(evt);
            }
        });
        mainpanel.add(lblreset);
        lblreset.setBounds(960, 440, 41, 40);

        jLabel1.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(98, 83, 74));
        jLabel1.setText("B I L L");
        mainpanel.add(jLabel1);
        jLabel1.setBounds(690, 50, 130, 50);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        bg.setForeground(new java.awt.Color(63, 49, 40));
        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashwi\\Documents\\NetBeansProjects\\bookStoreManagement\\src\\main\\java\\images\\sell_books.gif")); // NOI18N
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainpanel.add(bg);
        bg.setBounds(0, 0, 1060, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseClicked
        // TODO add your handling code here:
        Dashboard ref=new Dashboard();
        ref.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblhomeMouseClicked

    private void btnsearchMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnsearchMouseClicked
    {//GEN-HEADEREND:event_btnsearchMouseClicked
        // TODO add your handling code here:
        addToBill();
       
    }//GEN-LAST:event_btnsearchMouseClicked

    private void txtidActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtidActionPerformed
    {//GEN-HEADEREND:event_txtidActionPerformed
        // TODO add your handling code here:
        addToBill();
        txtid.setText("");
        
        
    }//GEN-LAST:event_txtidActionPerformed

    private void lblresetMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblresetMouseClicked
    {//GEN-HEADEREND:event_lblresetMouseClicked
        // TODO add your handling code here:
        resetBill();
        System.out.println("reset clicked");
        
    }//GEN-LAST:event_lblresetMouseClicked

    private void txtidFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtidFocusGained
    {//GEN-HEADEREND:event_txtidFocusGained
        // TODO add your handling code here:
        if(txtid.getText().equals("Enter Book ID"))
            txtid.setText("");
    }//GEN-LAST:event_txtidFocusGained

    private void lblgenerateBillMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblgenerateBillMouseClicked
    {//GEN-HEADEREND:event_lblgenerateBillMouseClicked
        try
        {
            // TODO add your handling code here:
            bp.txtareabooks.print();
            t.start();
            t=new Thread(this);
        } catch (PrinterException ex)
        {
            Logger.getLogger(sellBooks.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_lblgenerateBillMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sellBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sellBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sellBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sellBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sellBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLayeredPane billpane;
    private javax.swing.JLabel btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblgenerateBill;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lblreset;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
