/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author ashwi
 */
public class Statistics extends javax.swing.JFrame
{

        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form Statistics
     */
    public Statistics()
    {
        initComponents();
        conn=javaconnect.connerDb();
        showPieChart();
        
    }
    
    ////////////////////////////////
    public void showPieChart()
    {
        
        //create dataset
      DefaultPieDataset barDataset = new DefaultPieDataset( );
//      barDataset.setValue( "IPhone 5s" , new Double( 200 ) );  
//      barDataset.setValue( "SamSung Grand" , new Double( 120 ) );   
//      barDataset.setValue( "MotoG" , new Double( 407 ) );    
//      barDataset.setValue( "Nokia Lumia" , new Double( 310 ) );  


     String[] genreStrings={"romance","fiction","literature","academics","tragedy","history","biography"};
        
        
        for(int i=0;i<genreStrings.length;i++)
        {
              
            String sql="SELECT COUNT(*) FROM books WHERE Genre= '"+genreStrings[i]+"'";
            try
            {
                pst=conn.prepareStatement(sql);
                System.out.println("here");
                rs=pst.executeQuery();
                System.out.println("here2");

                int count=0;
                if(rs.next())
                {
                    count=rs.getInt(1);
                }
                
                barDataset.setValue( genreStrings[i], new Double( count ) ); 
               // System.out.println("**quantity of"+genreStrings[i]+" ::"+count);
            } 
            catch (SQLException ex)
            {
                System.out.println("error"+ex);

            }
        }

      //create chart
       JFreeChart piechart = ChartFactory.createPieChart("Book Genres",barDataset, false,true,false);//explain
      piechart.setBackgroundPaint(new Color(221, 193, 167));
        PiePlot piePlot =(PiePlot) piechart.getPlot();
      
      // changing pie chart blocks colors
//       piePlot.setSectionPaint("IPhone 5s", new Color(255,255,102));
//        piePlot.setSectionPaint("SamSung Grand", new Color(102,255,102));
//        piePlot.setSectionPaint("MotoG", new Color(255,102,153));
//        piePlot.setSectionPaint("Nokia Lumia", new Color(0,204,204));
//      
//       
        piePlot.setBackgroundPaint(Color.white);
        
        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        panelBarChart.removeAll();
        panelBarChart.add(barChartPanel, BorderLayout.CENTER);
        panelBarChart.validate();
    }
    ////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarChart = new javax.swing.JPanel();
        mainpanel = new javax.swing.JPanel();
        lblhome = new javax.swing.JLabel();
        lblbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1014, 568));
        setSize(new java.awt.Dimension(1014, 568));
        getContentPane().setLayout(null);

        panelBarChart.setBackground(new java.awt.Color(255, 204, 204));
        panelBarChart.setOpaque(false);
        panelBarChart.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelBarChart);
        panelBarChart.setBounds(520, 30, 470, 470);

        mainpanel.setLayout(null);
        getContentPane().add(mainpanel);
        mainpanel.setBounds(1287, 0, 0, 568);

        lblhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhomeMouseClicked(evt);
            }
        });
        getContentPane().add(lblhome);
        lblhome.setBounds(950, 510, 50, 50);
        getContentPane().add(lblbg);
        lblbg.setBounds(0, 0, 1281, 570);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblhomeMouseClicked
    {//GEN-HEADEREND:event_lblhomeMouseClicked
        // TODO add your handling code here:
        Dashboard ref=new Dashboard();
        ref.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblhomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblbg;
    private javax.swing.JLabel lblhome;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel panelBarChart;
    // End of variables declaration//GEN-END:variables
}
