/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

/**
 *
 * @author ashwi
 */
public class stock extends javax.swing.JFrame
{

    /**
     * Creates new form stock
     */
    public stock()
    {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainpanel = new javax.swing.JPanel();
        lblshowbooks = new javax.swing.JLabel();
        lbllowstock = new javax.swing.JLabel();
        table_pane = new javax.swing.JLayeredPane();
        lblcoverhome = new javax.swing.JLabel();
        lblhome = new javax.swing.JLabel();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainpanel.setBackground(new java.awt.Color(60, 86, 84));
        mainpanel.setAlignmentY(0.0F);
        mainpanel.setLayout(null);

        lblshowbooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblshowbooks.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblshowbooksMouseClicked(evt);
            }
        });
        mainpanel.add(lblshowbooks);
        lblshowbooks.setBounds(80, 110, 180, 130);

        lbllowstock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbllowstock.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lbllowstockMouseClicked(evt);
            }
        });
        mainpanel.add(lbllowstock);
        lbllowstock.setBounds(90, 310, 170, 150);

        table_pane.setBackground(new java.awt.Color(255, 204, 204));

        lblcoverhome.setBackground(new java.awt.Color(116, 94, 77));
        lblcoverhome.setOpaque(true);

        table_pane.setLayer(lblcoverhome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout table_paneLayout = new javax.swing.GroupLayout(table_pane);
        table_pane.setLayout(table_paneLayout);
        table_paneLayout.setHorizontalGroup(
            table_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, table_paneLayout.createSequentialGroup()
                .addContainerGap(678, Short.MAX_VALUE)
                .addComponent(lblcoverhome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        table_paneLayout.setVerticalGroup(
            table_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, table_paneLayout.createSequentialGroup()
                .addContainerGap(437, Short.MAX_VALUE)
                .addComponent(lblcoverhome, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        mainpanel.add(table_pane);
        table_pane.setBounds(302, 28, 751, 514);

        lblhome.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashwi\\Documents\\NetBeansProjects\\bookStoreManagement\\src\\main\\java\\images\\home.png")); // NOI18N
        lblhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblhome.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblhomeMouseClicked(evt);
            }
        });
        mainpanel.add(lblhome);
        lblhome.setBounds(30, 500, 60, 50);

        lblbackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashwi\\Documents\\NetBeansProjects\\bookStoreManagement\\src\\main\\java\\images\\stock_bg.png")); // NOI18N
        lblbackground.setDoubleBuffered(true);
        lblbackground.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblbackgroundMouseClicked(evt);
            }
        });
        mainpanel.add(lblbackground);
        lblbackground.setBounds(0, 0, 1070, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblbackgroundMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblbackgroundMouseClicked
    {//GEN-HEADEREND:event_lblbackgroundMouseClicked
        // TODO add your handling code here:
        
  
    }//GEN-LAST:event_lblbackgroundMouseClicked

    private void lblshowbooksMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblshowbooksMouseClicked
    {//GEN-HEADEREND:event_lblshowbooksMouseClicked
        // TODO add your handling code here:
        View_Database db=new View_Database();
        db.setBounds(0, 0,table_pane.getWidth(),table_pane.getHeight());
        CommonFunctions.switchPanel(table_pane,db);
    }//GEN-LAST:event_lblshowbooksMouseClicked

    private void lbllowstockMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbllowstockMouseClicked
    {//GEN-HEADEREND:event_lbllowstockMouseClicked
        // TODO add your handling code here:
         lowstockpanel lp=new lowstockpanel();
        lp.setBounds(0, 0,table_pane.getWidth(),table_pane.getHeight());
        CommonFunctions.switchPanel(table_pane,lp);
    }//GEN-LAST:event_lbllowstockMouseClicked

    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblhomeMouseClicked
    {//GEN-HEADEREND:event_lblhomeMouseClicked
        // TODO add your handling code here:
        Dashboard db=new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblhomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblcoverhome;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lbllowstock;
    private javax.swing.JLabel lblshowbooks;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JLayeredPane table_pane;
    // End of variables declaration//GEN-END:variables
}
