/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import source.Dashboard;

/**
 *
 * @author Lenovo
 */
public class update_data extends javax.swing.JFrame 
{

    /**
     * Creates new form update_data
     */
                  
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public update_data() 
    {
        initComponents();
        conn=javaconnect.connerDb();
        
    }
    private void cleardata()
    {
        System.out.println("in cleardata");
        txtbookname.setText("");
        txtauthor.setText("");
        txtid.setText("");
        txtgenre.setText("");
        txtprice.setText("");
        txtquantity.setText("");
    }
    public void updateData()
    {
        
        try 
        {
            
            int id=Integer.parseInt(txtid.getText());
            int quantity=Integer.parseInt(txtquantity.getText()); //entered by the user
            
             String sql="select * from books where Id="+id;
         
             pst=conn.prepareStatement(sql);
             rs=pst.executeQuery();
             
             if(rs.first())
             {
                 int quant=rs.getInt("Quantity"); //quantity froom database
                 quantity=quantity +quant;  //adding quantity of books from textfield to database
              
                 System.out.println(quant);
                 System.out.println(quantity);
                 
                 rs.close();
                pst.close();

                 sql="update books set Quantity ="+quantity+" where Id="+id;
                  
                 pst=conn.prepareStatement(sql);
                 pst.executeUpdate();
                 
                JOptionPane.showMessageDialog(null,"Updated!");
                 cleardata();
             }
             else
             {
                  String book =txtbookname.getText();
                  String author =txtauthor.getText();
                  String genre =txtgenre.getText();
                  int price =Integer.parseInt(txtprice.getText());
                  
                
                 pst.close();
              
                 // sql="INSERT INTO books VALUES ( "+id+","+book+","+author+","+genre+","+price+","+quantity+")"; 
                sql = "insert into books(Id,Name, Author,Genre,Price,Quantity) values(?, ?, ? , ?, ?,?)";
                pst = conn.prepareStatement(sql);
                pst.setInt(1,id);
                pst.setString(2, book);
                pst.setString(3, author);
                pst.setString(4,genre);
                pst.setInt(5,price);
                pst.setInt(6,quantity);
                pst.executeUpdate();
                
                cleardata();
                JOptionPane.showMessageDialog(null,"Updated!");
                 
                  
            
             }
             
             

        } 
        catch (Exception e) 
        {
           JOptionPane.showMessageDialog(null, "It is not connceted.");
            System.out.println(e);
  
        }
        
        finally
        {   
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        txtgenre = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        txtbookname = new javax.swing.JTextField();
        txtquantity = new javax.swing.JTextField();
        txtauthor = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        lblhome = new javax.swing.JLabel();
        lblbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1014, 568));
        setResizable(false);
        setSize(new java.awt.Dimension(1014, 568));

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(null);

        txtgenre.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txtgenre.setForeground(new java.awt.Color(189, 148, 121));
        txtgenre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtgenre);
        txtgenre.setBounds(500, 260, 380, 40);

        btnadd.setBackground(new java.awt.Color(189, 148, 121));
        btnadd.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("A D D");
        btnadd.setBorder(null);
        btnadd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd);
        btnadd.setBounds(240, 440, 660, 40);

        txtbookname.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txtbookname.setForeground(new java.awt.Color(189, 148, 121));
        txtbookname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbookname.setText("Enter  name of the book");
        jPanel1.add(txtbookname);
        txtbookname.setBounds(500, 80, 380, 40);

        txtquantity.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txtquantity.setForeground(new java.awt.Color(189, 148, 121));
        txtquantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtquantity);
        txtquantity.setBounds(500, 380, 380, 40);

        txtauthor.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txtauthor.setForeground(new java.awt.Color(189, 148, 121));
        txtauthor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtauthor);
        txtauthor.setBounds(500, 200, 380, 40);

        txtid.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txtid.setForeground(new java.awt.Color(189, 148, 121));
        txtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtid);
        txtid.setBounds(500, 140, 380, 40);

        txtprice.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txtprice.setForeground(new java.awt.Color(189, 148, 121));
        txtprice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtprice);
        txtprice.setBounds(500, 320, 380, 40);

        lblhome.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblhomeMouseClicked(evt);
            }
        });
        jPanel1.add(lblhome);
        lblhome.setBounds(940, 490, 60, 60);

        lblbg.setIcon(new javax.swing.ImageIcon("C:\\Users\\ashwi\\Documents\\NetBeansProjects\\bookStoreManagement\\src\\main\\java\\images\\update_books_bg.png")); // NOI18N
        jPanel1.add(lblbg);
        lblbg.setBounds(0, 0, 1020, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseClicked
        // TODO add your handling code here:
        Dashboard ref=new Dashboard();
        ref.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_lblhomeMouseClicked

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnaddActionPerformed
    {//GEN-HEADEREND:event_btnaddActionPerformed
        // TODO add your handling code here:
        updateData();
    }//GEN-LAST:event_btnaddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblbg;
    private javax.swing.JLabel lblhome;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtgenre;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtquantity;
    // End of variables declaration//GEN-END:variables
}
